require(gamlss)
curt <- function(x) return(x^(1.0/3))
fort <- function(x) return(x^(1.0/4))
square <- function(x) return(x^2)
#fit62 = gamlss(OBS~curt(MEAN) + OFFSET, sigma.formula=~MEAN + OFFSET, nu.formula=~MEAN+P05, family=ZAGA(), data=x)
#fit72 = gamlss(OBS~curt(ENS0) + OFFSET, sigma.formula=~ENS0 + OFFSET, nu.formula=~ENS0, family=ZAGA(), data=x)
#fit62a = gamlss(OBS~curt(MEAN) + OFFSET, sigma.formula=~MEAN + OFFSET, nu.formula=~MEAN+P05, family=ZAGA(), data=xa)
#fit64 = gamlss(OBS~curt(MEAN) + OFFSET, sigma.formula=~MEAN + OFFSET, nu.formula=~MEAN+P05+CP05, family=ZAGA(), data=x)
#fit65 = gamlss(OBS~curt(MEAN) + OFFSET, sigma.formula=~MEAN + OFFSET, nu.formula=~MEAN+CP05, family=ZAGA(), data=x)
#fit66 = gamlss(OBS~curt(MEAN) + OFFSET, sigma.formula=~MEAN + OFFSET, nu.formula=~MEAN+P05+P5, family=ZAGA(), data=x)
#fit67 = gamlss(OBS~curt(MEAN) + OFFSET, sigma.formula=~MEAN + OFFSET, nu.formula=~MEAN+P05+square(CP05), family=ZAGA(), data=x)
#fit68 = gamlss(OBS~curt(MEAN) + OFFSET, sigma.formula=~MEAN + OFFSET, nu.formula=~MEAN+P05+curt(MEAN)+CMEAN, family=ZAGA(), data=x)
#fit69 = gamlss(OBS~curt(MEAN) + OFFSET, sigma.formula=~MEAN + OFFSET, nu.formula=~MEAN+P05+curt(MEAN), family=ZAGA(), data=x)
I18 = which(x$OFFSET == 18)
I66 = which(x$OFFSET == 66)
I234 = which(x$OFFSET == 234)
#fit69_18  = gamlss(OBS~curt(MEAN) + OFFSET, sigma.formula=~MEAN + OFFSET, nu.formula=~MEAN+P05+curt(MEAN), family=ZAGA(), data=x[I18,])
#fit69_66  = gamlss(OBS~curt(MEAN) + OFFSET, sigma.formula=~MEAN + OFFSET, nu.formula=~MEAN+P05+curt(MEAN), family=ZAGA(), data=x[I66,])
#fit70_66  = gamlss(OBS~curt(MEAN), sigma.formula=~MEAN, nu.formula=~MEAN+P0+curt(MEAN), family=ZAGA(), data=x[I66,])
#fit71_66  = gamlss(OBS~curt(MEAN), sigma.formula=~MEAN, nu.formula=~MEAN+P0+P05+curt(MEAN), family=ZAGA(), data=x[I66,])
#fit72_66  = gamlss(OBS~curt(MEAN)+MEAN, sigma.formula=~MEAN+curt(MEAN), nu.formula=~MEAN+P0+P05+curt(MEAN), family=ZAGA(), data=x[I66,])
#fit73_66  = gamlss(OBS~curt(MEAN), sigma.formula=~MEAN+SD, nu.formula=~MEAN+P0+P05+curt(MEAN), family=ZAGA(), data=x[I66,])
#fit74_66  = gamlss(OBS~curt(MEAN), sigma.formula=~MEAN+P0+P05 +sqrt(MEAN), nu.formula=~MEAN+P0+P05+curt(MEAN), family=ZAGA(), data=x[I66,])
#fit75_66  = gamlss(OBS~sqrt(MEAN), sigma.formula=~MEAN, nu.formula=~MEAN+P05, family=ZAGA(), data=x[I66,])
#fit62_66  = gamlss(OBS~curt(MEAN), sigma.formula=~MEAN, nu.formula=~MEAN+P05, family=ZAGA(), data=x[I66,])
#fit76_66  = gamlss(OBS~MEAN, sigma.formula=~MEAN, nu.formula=~MEAN+P05, family=ZAGA(), data=x[I66,])
#fit77_66  = gamlss(OBS~fort(MEAN), sigma.formula=~MEAN, nu.formula=~MEAN+P05, family=ZAGA(), data=x[I66,])
#fit78_66  = gamlss(OBS~curt(MEAN), sigma.formula=~sqrt(MEAN), nu.formula=~MEAN+P05, family=ZAGA(), data=x[I66,])
#fit79_66  = gamlss(OBS~curt(MEAN), sigma.formula=~square(MEAN), nu.formula=~MEAN+P05, family=ZAGA(), data=x[I66,])
#fit80_66  = gamlss(OBS~curt(MEAN), sigma.formula=~MEAN+P0+P05+square(MEAN)+sqrt(P05), nu.formula=~MEAN+P05, family=ZAGA(), data=x[I66,])
#fit81_66  = gamlss(OBS~curt(MEAN)+curt(sqrt(MEAN)), sigma.formula=~MEAN, nu.formula=~MEAN+P05+curt(MEAN), family=ZAGA(), data=x[I66,])
#fit82_66  = gamlss(OBS~curt(MEAN)+ELEV, sigma.formula=~MEAN+ELEV, nu.formula=~MEAN+P05+curt(MEAN), family=ZAGA(), data=x[I66,])
#fit83_66  = gamlss(OBS~curt(MEAN)+LAT+LON, sigma.formula=~MEAN+LAT+LON, nu.formula=~MEAN+P05+curt(MEAN), family=ZAGA(), data=x[I66,])
#fit84_66  = gamlss(OBS~MEAN+sqrt(MEAN)+curt(MEAN)+fort(MEAN)+square(MEAN), sigma.formula=~MEAN, nu.formula=~MEAN+P05+curt(MEAN), family=ZAGA(), data=x[I66,])
#fit85_66  = gamlss(OBS~MEAN+sqrt(MEAN)+curt(MEAN)+fort(MEAN)+square(MEAN), sigma.formula=~MEAN+sqrt(MEAN)+curt(MEAN)+fort(MEAN)+square(MEAN), nu.formula=~MEAN+P05+curt(MEAN), family=ZAGA(), data=x[I66,])
#fit69_234 = gamlss(OBS~curt(MEAN), sigma.formula=~MEAN, nu.formula=~MEAN+P05+curt(MEAN), family=ZAGA(), data=x[I234,])
fit69     = gamlss(OBS~curt(MEAN), sigma.formula=~MEAN, nu.formula=~MEAN+P05+curt(MEAN), family=ZAGA(), data=x)

# Bad ideas
#fit82 = gamlss(OBS~curt(MEAN0) + OFFSET, sigma.formula=~MEAN0 + OFFSET, nu.formula=~MEAN0+P050, family=ZAGA(), data=x)
